-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.RU_XX (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("c <datetime> \1087\1086 <datetime> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.8602012652231115,
                               unseen = -3.4965075614664802,
                               likelihoods =
                                 HashMap.fromList
                                   [("MondayWednesday", -2.367123614131617),
                                    ("time-of-day (latent)time-of-day (latent)",
                                     -2.367123614131617),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal)",
                                     -1.5198257537444133),
                                    ("dayday", -1.1631508098056809),
                                    ("dd.mmdd.mm", -2.772588722239781),
                                    ("hourhour", -2.367123614131617)],
                               n = 11},
                   koData =
                     ClassData{prior = -0.5500463369192721, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)intersect", -2.5902671654458267),
                                    ("time-of-day (latent)time-of-day (latent)",
                                     -2.0794415416798357),
                                    ("dayday", -1.3862943611198906),
                                    ("<day-of-month> (ordinal)intersect", -2.3025850929940455),
                                    ("hourhour", -1.742969305058623),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal or number) <named-month>",
                                     -2.3025850929940455),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal or number) of <named-month>",
                                     -2.3025850929940455)],
                               n = 15}}),
       ("\1073\1077\1079 <integer> <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -0.8266785731844679),
                                    ("integer (numeric)time-of-day (latent)", -1.6739764335716716),
                                    ("integer (3..19)time-of-day (latent)", -1.3862943611198906),
                                    ("integer (20..90)time-of-day (latent)", -2.0794415416798357)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour diminutive",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.38299225225610584,
                               unseen = -4.919980925828125,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 135},
                   koData =
                     ClassData{prior = -1.1451323043030026, unseen = -4.174387269895637,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 63}}),
       ("integer (3..19)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.6109179126442243,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 35},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074 \1095\1072\1089",
        Classifier{okData =
                     ClassData{prior = -0.15415067982725836,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -1.9459101490553135,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("integer (20..90)",
        Classifier{okData =
                     ClassData{prior = -0.6190392084062235,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -0.7731898882334817,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("<day-of-month> (ordinal or number) <named-month>",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -4.174387269895637,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081May",
                                     -3.0602707946915624),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081September",
                                     -3.0602707946915624),
                                    ("integer (numeric)September", -3.0602707946915624),
                                    ("integer (numeric)May", -3.0602707946915624),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081March",
                                     -3.0602707946915624),
                                    ("month", -0.9400072584914712),
                                    ("integer (numeric)June", -3.4657359027997265),
                                    ("integer (numeric)October", -2.772588722239781),
                                    ("integer (numeric)January", -2.772588722239781),
                                    ("integer (numeric)March", -2.0794415416798357)],
                               n = 24},
                   koData =
                     ClassData{prior = -1.0986122886681098, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)May", -2.5902671654458267),
                                    ("ordinals (first..19th)September", -2.5902671654458267),
                                    ("ordinals (first..19th)February", -2.995732273553991),
                                    ("ordinals (first..19th)March", -2.3025850929940455),
                                    ("integer (numeric)February", -2.995732273553991),
                                    ("month", -1.1239300966523995),
                                    ("ordinals (20, 30,..,90)February", -2.995732273553991),
                                    ("integer (numeric)March", -2.5902671654458267)],
                               n = 12}}),
       ("<time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.1354942159291497,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -0.8938178760220964),
                                    ("tomorrowpart-of-days-2", -1.7047480922384253),
                                    ("\1074 <named-day>part-of-days-2", -2.3978952727983707),
                                    ("todaypart-of-days-2", -2.3978952727983707),
                                    ("day-after-tomorrowpart-of-days-2", -1.9924301646902063),
                                    ("Mondaypart-of-days-2", -2.3978952727983707)],
                               n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("numbers prefix with -, minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 1}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("at <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.25489224962879004,
                               unseen = -5.575949103146316,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> \1085\1086\1083\1100 0..9", -4.185859671057874),
                                    ("<time-of-day> <part-of-day>", -2.7389406881215486),
                                    ("half-short <hour-of-day-ordinal>", -4.473541743509655),
                                    ("<hour-of-day> <integer>", -2.6817822742815998),
                                    ("<hour-of-day> \1085\1086\1083\1100 0..9 \1084\1080\1085\1091\1090",
                                     -4.879006851617819),
                                    ("time-of-day (latent)", -1.7435126356886697),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090",
                                     -3.9627161197436642),
                                    ("hh:mm", -2.394100201829819),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)", -3.374929454841545),
                                    ("half-long <hour-of-day-ordinal>", -4.879006851617819),
                                    ("N \1095\1072\1089 (1..4, 22..23)", -4.185859671057874),
                                    ("hour", -1.338047527580505), ("minute", -1.5291027643432145),
                                    ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
                                     -4.879006851617819)],
                               n = 124},
                   koData =
                     ClassData{prior = -1.491654876777717, unseen = -4.477336814478207,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> <integer>", -2.856470206220483),
                                    ("time-of-day (latent)", -1.0001722158548572),
                                    ("hhmm (latent)", -3.7727609380946383),
                                    ("hour", -1.0001722158548572), ("minute", -2.6741486494265287)],
                               n = 36}}),
       ("September",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 1",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> \1087\1086\1087\1086\1083\1091\1076\1085\1080",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("N \1095\1072\1089 (1..4, 22..23)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("until <day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -0.9444616088408514,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.5108256237659907),
                                    ("ordinals (first..19th)", -1.2039728043259361)],
                               n = 7},
                   koData =
                     ClassData{prior = -0.49247648509779407, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.8472978603872037),
                                    ("ordinals (20, 30,..,90)", -1.540445040947149),
                                    ("ordinals (first..19th)", -1.0296194171811581)],
                               n = 11}}),
       ("October",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("January",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1053\1086\1074\1099\1081 \1075\1086\1076",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Wednesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1056\1086\1078\1076\1077\1089\1090\1074\1086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> \1085\1086\1083\1100 0..9",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer (numeric)", -2.1972245773362196),
                                    ("time-of-day (latent)integer 0", -2.1972245773362196),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)integer 0",
                                     -2.1972245773362196),
                                    ("hour", -0.9444616088408514),
                                    ("at <time-of-day>integer (numeric)", -2.1972245773362196),
                                    ("at <time-of-day>integer 0", -1.791759469228055)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.16989903679539747,
                               unseen = -4.820281565605037,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1073\1077\1079 <integer> <hour-of-day>",
                                     -3.4258899942525267),
                                    ("\1074 \1095\1072\1089", -3.4258899942525267),
                                    ("at <time-of-day>", -1.9789710113162013),
                                    ("<hour-of-day> \1085\1086\1083\1100 0..9", -3.713572066704308),
                                    ("\1073\1077\1079 \1095\1077\1090\1074\1077\1088\1090\1080 <hour-of-day>",
                                     -3.713572066704308),
                                    ("half-short <hour-of-day-ordinal>", -3.202746442938317),
                                    ("<hour-of-day> <integer>", -2.866274206317104),
                                    ("time-of-day (latent)", -2.2472349979108808),
                                    ("hh:mm", -4.119037174812472),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)", -4.119037174812472),
                                    ("N \1095\1072\1089 (1..4, 22..23)", -3.713572066704308),
                                    ("hour", -1.3464484525726907), ("minute", -1.6341305250244718),
                                    ("\1088\1086\1074\1085\1086|\1090\1086\1095\1085\1086 <time-of-day>",
                                     -4.119037174812472),
                                    ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
                                     -4.119037174812472)],
                               n = 54},
                   koData =
                     ClassData{prior = -1.8562979903656263, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> <integer>", -2.456735772821304),
                                    ("time-of-day (latent)", -1.3581234841531944),
                                    ("hour", -1.3581234841531944), ("minute", -2.456735772821304)],
                               n = 10}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = -1.8718021769015913, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.1670540846631662,
                               unseen = -3.1780538303479458,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 22}}),
       ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<year> (latent)",
        Classifier{okData =
                     ClassData{prior = -1.2192402764567243,
                               unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList [("integer (numeric)", -0.25131442828090605)],
                               n = 13},
                   koData =
                     ClassData{prior = -0.35020242943311486,
                               unseen = -3.6109179126442243,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.8109302162163288),
                                    ("integer (20..90)", -1.791759469228055),
                                    ("numbers prefix with -, minus", -2.890371757896165),
                                    ("integer 21..99", -2.4849066497880004),
                                    ("integer 0", -1.3862943611198906)],
                               n = 31}}),
       ("\1074\1099\1093\1086\1076\1085\1099\1077",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("until <day-of-month>",
        Classifier{okData =
                     ClassData{prior = -1.575536360758419, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("<day-of-month> (ordinal or number) <named-month>",
                                     -2.2512917986064953),
                                    ("<day-of-month> (ordinal or number) of <named-month>",
                                     -2.2512917986064953),
                                    ("day", -0.9985288301111273),
                                    ("<day-of-month> (ordinal)", -1.845826690498331),
                                    ("dd.mm", -1.845826690498331)],
                               n = 6},
                   koData =
                     ClassData{prior = -0.2318016140573243,
                               unseen = -3.9889840465642745,
                               likelihoods =
                                 HashMap.fromList
                                   [("<day-of-month> (ordinal or number) <named-month>",
                                     -2.0243817644968085),
                                    ("Wednesday", -3.2771447329921766),
                                    ("intersect", -2.583997552432231),
                                    ("<day-of-month> (ordinal or number) of <named-month>",
                                     -2.0243817644968085),
                                    ("day", -0.7922380832041762),
                                    ("<day-of-month> (ordinal)", -2.0243817644968085),
                                    ("dd.mm", -3.2771447329921766)],
                               n = 23}}),
       ("\1073\1077\1079 \1095\1077\1090\1074\1077\1088\1090\1080 <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half-short <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("", -0.8472978603872037),
                                    ("ordinals (first..19th)", -0.5596157879354228)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("May",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.8383291904044432, unseen = -5.783825182329737,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle><time-of-day> <part-of-day>",
                                     -5.0875963352323845),
                                    ("hourday", -3.295836866004329),
                                    ("dayhour", -2.0918640616783932),
                                    ("daymonth", -2.7850112422383386),
                                    ("monthyear", -3.58351893845611),
                                    ("tomorrowpart-of-days-2", -4.394449154672439),
                                    ("\1089 <day-of-month> \1087\1086 <day-of-month> (interval)March",
                                     -4.394449154672439),
                                    ("until <day-of-month> (ordinal)March", -5.0875963352323845),
                                    ("intersectat <time-of-day>", -3.58351893845611),
                                    ("on <day>May", -5.0875963352323845),
                                    ("<day-of-month> (ordinal)September", -4.68213122712422),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090intersect",
                                     -4.68213122712422),
                                    ("part-of-days-2<hour-of-day> <integer>", -5.0875963352323845),
                                    ("<time-of-day> <part-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -4.68213122712422),
                                    ("October<year> \1075\1086\1076 (latent)", -4.68213122712422),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month>(ordinal or number)/<named-month>/<year>",
                                     -4.68213122712422),
                                    ("October<year> (latent)", -4.394449154672439),
                                    ("todayat <time-of-day>", -4.68213122712422),
                                    ("at <time-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -4.68213122712422),
                                    ("<day-of-month> (ordinal)May", -4.68213122712422),
                                    ("<day-of-month> (ordinal or number) <named-month>at <time-of-day>",
                                     -5.0875963352323845),
                                    ("<time> <part-of-day>at <time-of-day>", -4.68213122712422),
                                    ("on <day>September", -5.0875963352323845),
                                    ("\1074 <named-day>part-of-days-2", -5.0875963352323845),
                                    ("hourhour", -4.394449154672439),
                                    ("dayyear", -3.2157941583307927),
                                    ("hourminute", -3.834833366737016),
                                    ("intersect<hour-of-day> <integer>", -5.0875963352323845),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>at <time-of-day>",
                                     -5.0875963352323845),
                                    ("at <time-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -4.68213122712422),
                                    ("part-of-days-2at <time-of-day>", -4.68213122712422),
                                    ("todaypart-of-days-2", -5.0875963352323845),
                                    ("\1074(\1090\1077\1095\1077\1085\1080\1077)/\1085\1072 <named-month>|year<year> \1075\1086\1076 (latent)",
                                     -5.0875963352323845),
                                    ("<time-of-day> <part-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -4.68213122712422),
                                    ("tomorrowintersect", -4.394449154672439),
                                    ("<time> <part-of-day><hour-of-day> <integer>",
                                     -5.0875963352323845),
                                    ("<day-of-month> (ordinal or number) of <named-month><year> (latent)",
                                     -3.834833366737016),
                                    ("intersect<time-of-day> <part-of-day>", -4.68213122712422),
                                    ("intersect<year> (latent)", -4.68213122712422),
                                    ("day-after-tomorrowpart-of-days-2", -4.68213122712422),
                                    ("dayminute", -3.834833366737016),
                                    ("dd.mm.yyhh:mm", -5.0875963352323845),
                                    ("on <day>March", -5.0875963352323845),
                                    ("minuteday", -3.834833366737016),
                                    ("<day-of-month> (ordinal or number) <named-month><year> (latent)",
                                     -3.834833366737016),
                                    ("<day-of-month>(ordinal or number)/<named-month>/<year>at <time-of-day>",
                                     -3.834833366737016),
                                    ("today<time-of-day> <part-of-day>", -5.0875963352323845),
                                    ("part-of-days-2\1074 <named-day>", -5.0875963352323845),
                                    ("<day-of-month> (ordinal)March", -4.68213122712422),
                                    ("c <datetime> \1087\1086 <datetime> (interval)February",
                                     -4.68213122712422),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month> (ordinal or number) <named-month>",
                                     -5.0875963352323845),
                                    ("<day-of-month>(ordinal or number)/<named-month>/<year><time-of-day> <part-of-day>",
                                     -4.68213122712422),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) <named-month>",
                                     -5.0875963352323845),
                                    ("tomorrow<time-of-day> <part-of-day>", -5.0875963352323845),
                                    ("tomorrowat <time-of-day>", -3.4781584227982836),
                                    ("Mondaypart-of-days-2", -5.0875963352323845),
                                    ("\1089 <day-of-month> \1087\1086 <day-of-month> (interval)February",
                                     -4.394449154672439),
                                    ("<day-of-month> (ordinal or number) of <named-month>at <time-of-day>",
                                     -5.0875963352323845),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month> (ordinal or number) of <named-month>",
                                     -5.0875963352323845),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) of <named-month>",
                                     -5.0875963352323845),
                                    ("\1074(\1090\1077\1095\1077\1085\1080\1077)/\1085\1072 <named-month>|year<year> (latent)",
                                     -4.68213122712422),
                                    ("c <datetime> \1087\1086 <datetime> (interval)March",
                                     -5.0875963352323845),
                                    ("minuteyear", -4.68213122712422)],
                               n = 112},
                   koData =
                     ClassData{prior = -0.5663954749208014, unseen = -5.978885764901122,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -2.3654329966537095),
                                    ("dayhour", -3.896909367618098),
                                    ("daymonth", -3.031911930131493),
                                    ("monthyear", -4.03044076024262),
                                    ("N \1095\1072\1089 (1..4, 22..23)<year> (latent)",
                                     -5.2832037287379885),
                                    ("March<year> (latent)", -4.877738620629824),
                                    ("houryear", -2.392831970841824),
                                    ("until <day-of-month> (ordinal)March", -4.590056548178043),
                                    ("intersectat <time-of-day>", -4.366912996863833),
                                    ("at <time-of-day>March", -5.2832037287379885),
                                    ("<day-of-month> (ordinal)September", -4.877738620629824),
                                    ("time-of-day (latent)intersect", -3.4914442595099335),
                                    ("time-of-day (latent)October", -4.590056548178043),
                                    ("time-of-day (latent)January", -4.877738620629824),
                                    ("monthhour", -4.1845914400698785),
                                    ("hourmonth", -2.42100284780852),
                                    ("October<year> (latent)", -4.877738620629824),
                                    ("todayat <time-of-day>", -5.2832037287379885),
                                    ("at <time-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -4.877738620629824),
                                    ("January<year> (latent)", -5.2832037287379885),
                                    ("<day-of-month> (ordinal)May", -4.877738620629824),
                                    ("\1089|\1087\1086\1089\1083\1077 <time>February",
                                     -5.2832037287379885),
                                    ("<time> <part-of-day>at <time-of-day>", -5.2832037287379885),
                                    ("intersectMarch", -4.877738620629824),
                                    ("time-of-day (latent)September", -4.877738620629824),
                                    ("hourhour", -4.590056548178043),
                                    ("until <day-of-month>March", -5.2832037287379885),
                                    ("time-of-day (latent)February", -5.2832037287379885),
                                    ("time-of-day (latent)June", -5.2832037287379885),
                                    ("minutemonth", -4.590056548178043),
                                    ("June<year> (latent)", -5.2832037287379885),
                                    ("\1089|\1087\1086\1089\1083\1077 <time>March",
                                     -5.2832037287379885),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>at <time-of-day>",
                                     -5.2832037287379885),
                                    ("<day-of-month> (ordinal)February", -4.877738620629824),
                                    ("at <time-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -4.877738620629824),
                                    ("part-of-days-2at <time-of-day>", -5.2832037287379885),
                                    ("tomorrowintersect", -5.2832037287379885),
                                    ("intersect<time-of-day> <part-of-day>", -5.2832037287379885),
                                    ("intersect<year> (latent)", -3.7791263319617143),
                                    ("at <time-of-day>intersect", -4.877738620629824),
                                    ("time-of-day (latent)until <day-of-month>",
                                     -4.1845914400698785),
                                    ("Marchat <time-of-day>", -5.2832037287379885),
                                    ("time-of-day (latent)March", -3.673765816303888),
                                    ("at <time-of-day><year> (latent)", -2.980618635743943),
                                    ("at <time-of-day>January", -5.2832037287379885),
                                    ("<day-of-month> (ordinal)March", -4.590056548178043),
                                    ("until <time>March", -5.2832037287379885),
                                    ("c <datetime> \1087\1086 <datetime> (interval)February",
                                     -5.2832037287379885),
                                    ("time-of-day (latent)until <day-of-month> (ordinal)",
                                     -4.590056548178043),
                                    ("at <time-of-day>September", -5.2832037287379885),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)<year> (latent)",
                                     -3.896909367618098),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) <named-month>",
                                     -4.366912996863833),
                                    ("until <day-of-month> (ordinal)February", -4.590056548178043),
                                    ("\1089|\1087\1086\1089\1083\1077 <time>until <day-of-month> (ordinal)",
                                     -4.877738620629824),
                                    ("tomorrowat <time-of-day>", -4.366912996863833),
                                    ("until <day-of-month>February", -4.877738620629824),
                                    ("\1089|\1087\1086\1089\1083\1077 <time>until <day-of-month>",
                                     -4.366912996863833),
                                    ("intersectFebruary", -4.877738620629824),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) of <named-month>",
                                     -4.366912996863833),
                                    ("\1089|\1087\1086\1089\1083\1077 <time>intersect",
                                     -4.877738620629824),
                                    ("c <datetime> \1087\1086 <datetime> (interval)March",
                                     -5.2832037287379885),
                                    ("<hour-of-day> <integer>January", -4.877738620629824)],
                               n = 147}}),
       ("ordinals (20, 30,..,90)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = -0.4700036292457356,
                               unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("integer 21..99",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (20..90)integer (3..19)", -0.5108256237659907),
                                    ("integer (20..90)integer 2", -0.916290731874155)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.3862943611198906,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (20..90)integer (3..19)", -0.40546510810816444)],
                               n = 1}}),
       ("\1089\1087\1091\1089\1090\1103 <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("second", -1.791759469228055),
                                    ("<integer> \1089\1091\1090\1086\1082", -1.791759469228055),
                                    ("a <unit-of-duration>", -1.791759469228055),
                                    ("hour", -1.791759469228055), ("month", -1.791759469228055),
                                    ("<positive-numeral> <time-grain>", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074(\1090\1077\1095\1077\1085\1080\1077) <named-month>|year \1075\1086\1076\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("<year> (latent)", -0.6931471805599453),
                                    ("year", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Monday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1095\1077\1090\1074\1077\1088\1090\1100 <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("ordinals (first..19th)", 0.0)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm:ss",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("dd.mm.yy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> <integer>",
        Classifier{okData =
                     ClassData{prior = -0.23767165187711958,
                               unseen = -4.564348191467836,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>integer 21..99", -3.455264602932431),
                                    ("\1074 \1095\1072\1089integer (numeric)", -3.455264602932431),
                                    ("at <time-of-day>integer (20..90)", -3.455264602932431),
                                    ("time-of-day (latent)integer (numeric)", -1.988927534139004),
                                    ("time-of-day (latent)integer (3..19)", -3.455264602932431),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)integer (numeric)",
                                     -3.1675825304806504),
                                    ("time-of-day (latent)integer 21..99", -3.455264602932431),
                                    ("hour", -0.8162072733171726),
                                    ("at <time-of-day>integer (numeric)", -2.0689702418125404),
                                    ("at <time-of-day>integer (3..19)", -3.455264602932431),
                                    ("time-of-day (latent)integer (20..90)", -3.1675825304806504)],
                               n = 41},
                   koData =
                     ClassData{prior = -1.5533484457830569, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>integer 2", -2.8622008809294686),
                                    ("at <time-of-day>integer (20..90)", -2.456735772821304),
                                    ("time-of-day (latent)integer (numeric)", -2.169053700369523),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)integer (numeric)",
                                     -2.8622008809294686),
                                    ("hour", -1.0704414117014134),
                                    ("time-of-day (latent)integer 2", -2.8622008809294686),
                                    ("at <time-of-day>integer (numeric)", -2.8622008809294686),
                                    ("time-of-day (latent)integer (20..90)", -2.456735772821304)],
                               n = 11}}),
       ("<duration> \1089\1087\1091\1089\1090\1103|\1085\1072\1079\1072\1076",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("second", -1.791759469228055),
                                    ("<integer> \1089\1091\1090\1086\1082", -1.791759469228055),
                                    ("a <unit-of-duration>", -1.791759469228055),
                                    ("hour", -1.791759469228055), ("month", -1.791759469228055),
                                    ("<positive-numeral> <time-grain>", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("a <unit-of-duration>", -1.3862943611198906),
                                    ("hour", -1.3862943611198906)],
                               n = 1}}),
       ("\1074(\1090\1077\1095\1077\1085\1080\1077)/\1085\1072 <named-month>|year",
        Classifier{okData =
                     ClassData{prior = -0.3794896217049037,
                               unseen = -3.4965075614664802,
                               likelihoods =
                                 HashMap.fromList
                                   [("October", -2.367123614131617),
                                    ("<year> (latent)", -1.8562979903656263),
                                    ("year", -0.9808292530117262),
                                    ("<year> \1075\1086\1076 (latent)", -2.0794415416798357),
                                    ("month", -2.367123614131617),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>",
                                     -1.8562979903656263)],
                               n = 13},
                   koData =
                     ClassData{prior = -1.1526795099383855,
                               unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("<year> (latent)", -0.9444616088408514),
                                    ("year", -0.9444616088408514)],
                               n = 6}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> \1085\1086\1083\1100 0..9 \1084\1080\1085\1091\1090",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("N \1095\1072\1089\1086\1074 (0, 5..20)integer 0",
                                     -1.252762968495368),
                                    ("hour", -0.8472978603872037),
                                    ("at <time-of-day>integer 0", -1.252762968495368)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1083\1076\1077\1085\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal or number) of <named-month>",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -4.174387269895637,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081May",
                                     -3.0602707946915624),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081September",
                                     -3.0602707946915624),
                                    ("integer (numeric)September", -3.0602707946915624),
                                    ("integer (numeric)May", -3.0602707946915624),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081March",
                                     -3.0602707946915624),
                                    ("month", -0.9400072584914712),
                                    ("integer (numeric)June", -3.4657359027997265),
                                    ("integer (numeric)October", -2.772588722239781),
                                    ("integer (numeric)January", -2.772588722239781),
                                    ("integer (numeric)March", -2.0794415416798357)],
                               n = 24},
                   koData =
                     ClassData{prior = -1.0986122886681098, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)May", -2.5902671654458267),
                                    ("ordinals (first..19th)September", -2.5902671654458267),
                                    ("ordinals (first..19th)February", -2.995732273553991),
                                    ("ordinals (first..19th)March", -2.3025850929940455),
                                    ("integer (numeric)February", -2.995732273553991),
                                    ("month", -1.1239300966523995),
                                    ("ordinals (20, 30,..,90)February", -2.995732273553991),
                                    ("integer (numeric)March", -2.5902671654458267)],
                               n = 12}}),
       ("\1101\1090\1086\1090 <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (grain)", -0.6931471805599453),
                                    ("year", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.639057329615259,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1089 <time-of-day> \1076\1086 <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)time-of-day (latent)",
                                     -0.6931471805599453),
                                    ("hourhour", -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("by <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -1.0296194171811581),
                                    ("hh:mm", -1.9459101490553135), ("hour", -1.0296194171811581),
                                    ("minute", -1.9459101490553135)],
                               n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("June",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1089|\1087\1086\1089\1083\1077 <time>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -4.02535169073515,
                               likelihoods =
                                 HashMap.fromList
                                   [("intersect", -1.6094379124341003),
                                    ("Monday", -2.908720896564361), ("day", -1.8101086078962516),
                                    ("time-of-day (latent)", -2.0614230361771577),
                                    ("<day-of-month> (ordinal)", -2.2155737160044158),
                                    ("hour", -1.1741198411762548), ("dd.mm", -3.3141860046725258)],
                               n = 24}}),
       ("February",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> \1089\1091\1090\1086\1082",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = -1.0498221244986778,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -0.4307829160924542, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13}}),
       ("time-of-day (latent)",
        Classifier{okData =
                     ClassData{prior = -0.5893503868783018, unseen = -4.330733340286331,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.4673405118262518),
                                    ("integer (3..19)", -1.0986122886681098),
                                    ("integer 21..99", -3.624340932976365)],
                               n = 71},
                   koData =
                     ClassData{prior = -0.808978996085067, unseen = -4.127134385045092,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.15963014559188396),
                                    ("integer (3..19)", -3.417726683613366),
                                    ("integer (20..90)", -2.3191143949452564)],
                               n = 57}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -1.4816045409242156, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.6094379124341003),
                                    ("integer 2week (grain)", -2.456735772821304),
                                    ("integer (numeric)week (grain)", -1.9459101490553135),
                                    ("integer (3..19)minute (grain)", -2.8622008809294686),
                                    ("integer (numeric)minute (grain)", -2.169053700369523),
                                    ("minute", -1.9459101490553135)],
                               n = 10},
                   koData =
                     ClassData{prior = -0.2578291093020998, unseen = -4.430816798843313,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)day (grain)", -2.8094026953624978),
                                    ("integer (3..19)day (grain)", -3.7256934272366524),
                                    ("integer 1hour (grain)", -3.7256934272366524),
                                    ("integer (numeric)year (grain)", -2.627081138568543),
                                    ("day", -2.627081138568543), ("year", -2.627081138568543),
                                    ("hour", -1.6462518855568167),
                                    ("integer (numeric)minute (grain)", -2.1162555148025524),
                                    ("integer (3..19)hour (grain)", -3.0325462466767075),
                                    ("minute", -2.1162555148025524),
                                    ("integer (numeric)hour (grain)", -1.9339339580085977)],
                               n = 34}}),
       ("<year> \1075\1086\1076 (latent)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinals (first..19th)",
        Classifier{okData =
                     ClassData{prior = -0.2231435513142097, unseen = -3.258096538021482,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 24},
                   koData =
                     ClassData{prior = -1.6094379124341003,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("hhmm (latent)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<cycle> \1095\1077\1088\1077\1079 <count>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("minute (grain)integer (3..19)", -1.252762968495368),
                                    ("minute (grain)integer (numeric)", -1.252762968495368),
                                    ("minute", -0.8472978603872037)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> <integer> \1084\1080\1085\1091\1090",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.4657359027997265,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer (numeric)", -2.740840023925201),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)integer (numeric)",
                                     -1.824549292051046),
                                    ("N \1095\1072\1089 (1..4, 22..23)integer (numeric)",
                                     -2.740840023925201),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)integer 0",
                                     -2.3353749158170367),
                                    ("hour", -0.8690378470236094),
                                    ("at <time-of-day>integer (numeric)", -2.3353749158170367),
                                    ("at <time-of-day>integer 0", -2.3353749158170367)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("on <day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.7376696182833684,
                               likelihoods =
                                 HashMap.fromList
                                   [("<day-of-month> (ordinal or number) <named-month>",
                                     -1.7676619176489945),
                                    ("intersect", -2.327277705584417),
                                    ("<day-of-month> (ordinal or number) of <named-month>",
                                     -1.7676619176489945),
                                    ("day", -0.7691330875378672),
                                    ("<day-of-month> (ordinal)", -2.327277705584417)],
                               n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("a <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -2.472930458741285, unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.159484249353372),
                                    ("month (grain)", -1.8718021769015913),
                                    ("hour (grain)", -2.5649493574615367),
                                    ("week (grain)", -2.159484249353372),
                                    ("minute (grain)", -2.5649493574615367),
                                    ("hour", -2.5649493574615367), ("month", -1.8718021769015913),
                                    ("minute", -2.5649493574615367)],
                               n = 7},
                   koData =
                     ClassData{prior = -8.81072675102669e-2, unseen = -5.10594547390058,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -3.153956278768885),
                                    ("hour (grain)", -1.8417698898027164),
                                    ("year (grain)", -2.2666530837679826),
                                    ("week (grain)", -3.153956278768885),
                                    ("day", -2.7019711550258276),
                                    ("minute (grain)", -2.1041341542702074),
                                    ("year", -2.2666530837679826), ("hour", -1.8417698898027164),
                                    ("minute", -2.1041341542702074),
                                    ("day (grain)", -2.7019711550258276)],
                               n = 76}}),
       ("hh:mm",
        Classifier{okData =
                     ClassData{prior = -3.7740327982847086e-2,
                               unseen = -3.332204510175204,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 26},
                   koData =
                     ClassData{prior = -3.295836866004329, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("\1089 <day-of-month> \1087\1086 <day-of-month> (interval)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)ordinals (20, 30,..,90)",
                                     -1.540445040947149),
                                    ("integer (numeric)integer (numeric)", -1.252762968495368),
                                    ("ordinals (first..19th)ordinals (first..19th)",
                                     -1.0296194171811581),
                                    ("ordinals (first..19th)integer (numeric)",
                                     -1.9459101490553135)],
                               n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1085\1072 \1087\1088\1086\1096\1077\1076\1096\1077\1081 <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1074\1099\1093\1086\1076\1085\1099\1077",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("N \1095\1072\1089\1086\1074 (0, 5..20)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.3746934494414107),
                                    ("integer (3..19)", -1.6739764335716716),
                                    ("integer 0", -2.0794415416798357)],
                               n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute diminutive",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter of an hour",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month>(ordinal or number)/<named-month>/<year>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.5553480614894135,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)January<year> (latent)", -2.833213344056216),
                                    ("integer (numeric)October<year> (latent)",
                                     -2.4277482359480516),
                                    ("monthyear", -1.580450375560848),
                                    ("integer (numeric)March<year> (latent)", -2.4277482359480516),
                                    ("integer (numeric)June<year> (latent)", -2.833213344056216),
                                    ("month", -1.580450375560848),
                                    ("integer (numeric)June", -2.833213344056216),
                                    ("integer (numeric)October", -2.4277482359480516),
                                    ("integer (numeric)January", -2.833213344056216),
                                    ("integer (numeric)March", -2.4277482359480516)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1089 <day-of-month> (ordinal or number) \1076\1086 <day-of-month> (ordinal or number) <named-month> (interval)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)ordinals (20, 30,..,90)February",
                                     -2.1972245773362196),
                                    ("integer (numeric)integer (numeric)February",
                                     -2.1972245773362196),
                                    ("ordinals (first..19th)ordinals (first..19th)February",
                                     -2.1972245773362196),
                                    ("ordinals (first..19th)ordinals (first..19th)March",
                                     -2.1972245773362196),
                                    ("integer (numeric)integer (numeric)March", -1.791759469228055),
                                    ("month", -0.9444616088408514)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("until <time>",
        Classifier{okData =
                     ClassData{prior = -1.5040773967762742,
                               unseen = -2.4849066497880004,
                               likelihoods =
                                 HashMap.fromList
                                   [("<day-of-month> (ordinal or number) <named-month>",
                                     -1.7047480922384253),
                                    ("<day-of-month> (ordinal or number) of <named-month>",
                                     -1.7047480922384253),
                                    ("day", -1.2992829841302609)],
                               n = 2},
                   koData =
                     ClassData{prior = -0.25131442828090605,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -2.3513752571634776),
                                    ("intersect", -2.3513752571634776),
                                    ("day", -2.3513752571634776),
                                    ("time-of-day (latent)", -1.252762968495368),
                                    ("hour", -1.0986122886681098)],
                               n = 7}}),
       ("half-long <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("ordinals (first..19th)", 0.0)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("March",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.639057329615259,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("N \1095\1072\1089 (1..4, 22..23)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.8472978603872037),
                                    ("integer (3..19)", -1.252762968495368),
                                    ("integer 1", -1.252762968495368)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -0.3285040669720361,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081",
                                     -1.0986122886681098),
                                    ("ordinals (20, 30,..,90)", -1.9459101490553135),
                                    ("ordinals (first..19th)", -0.6466271649250525)],
                               n = 18},
                   koData =
                     ClassData{prior = -1.2729656758128873,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList [("ordinals (first..19th)", -0.2231435513142097)],
                               n = 7}}),
       ("\1095\1077\1088\1077\1079|\1074 \1090\1077\1095\1077\1085\1080\1077|\1087\1086\1089\1083\1077 <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.07753744390572,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour diminutive", -2.6741486494265287),
                                    ("week", -1.8632184332102), ("second", -3.367295829986474),
                                    ("<integer> \1089\1091\1090\1086\1082", -3.367295829986474),
                                    ("<integer> <unit-of-duration>", -1.6625477377480489),
                                    ("a <unit-of-duration>", -2.268683541318364),
                                    ("minute diminutive", -2.9618307218783095),
                                    ("quarter of an hour", -3.367295829986474),
                                    ("hour", -2.268683541318364), ("month", -3.367295829986474),
                                    ("minute", -1.8632184332102),
                                    ("<positive-numeral> <time-grain>", -3.367295829986474)],
                               n = 23},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day-before-yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("decimal number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("decimal one and a half",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1083\1085\1086\1095\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 0",
        Classifier{okData =
                     ClassData{prior = -0.4700036292457356,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (grain)", -0.8754687373538999),
                                    ("day", -2.4849066497880004), ("year", -0.8754687373538999),
                                    ("day (grain)", -2.4849066497880004)],
                               n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074 <named-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -0.6931471805599453), ("day", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -2.3025850929940455,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.10536051565782628,
                               unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9}}),
       ("part-of-days-2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("dd.mm",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("right now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1088\1086\1074\1085\1086|\1090\1086\1095\1085\1086 <time-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.3862943611198906),
                                    ("<time-of-day> <part-of-day>", -1.791759469228055),
                                    ("hour", -0.8754687373538999),
                                    ("\1087\1086\1083\1085\1086\1095\1100", -1.791759469228055)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("composite <duration>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourminute", -0.6931471805599453),
                                    ("integer (numeric)hour (grain)<integer> <unit-of-duration>",
                                     -0.6931471805599453)],
                               n = 4}}),
       ("day-after-tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)ordinals (first..19th)", 0.0)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<positive-numeral> <time-grain>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("decimal one and a halfhour (grain)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}})]