-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.RU_XX (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("c <datetime> \1087\1086 <datetime> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.9650808960435872, unseen = -3.258096538021482,
                               likelihoods =
                                 HashMap.fromList
                                   [("MondayWednesday", -2.120263536200091),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal)",
                                     -1.2729656758128873),
                                    ("dayday", -1.0216512475319814)],
                               n = 8},
                   koData =
                     ClassData{prior = -0.4795730802618862, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)intersect", -2.456735772821304),
                                    ("time-of-day (latent)time-of-day (latent)",
                                     -2.456735772821304),
                                    ("dayday", -1.252762968495368),
                                    ("<day-of-month> (ordinal)intersect", -2.169053700369523),
                                    ("hourhour", -1.9459101490553135),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal or number) <named-month>",
                                     -2.169053700369523),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal or number) of <named-month>",
                                     -2.169053700369523)],
                               n = 13}}),
       ("\1073\1077\1079 <integer> <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -0.8266785731844679),
                                    ("integer (numeric)time-of-day (latent)", -1.6739764335716716),
                                    ("integer (3..19)time-of-day (latent)", -1.3862943611198906),
                                    ("integer (20..90)time-of-day (latent)", -2.0794415416798357)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour diminutive",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.3671042402357181, unseen = -4.836281906951478,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 124},
                   koData =
                     ClassData{prior = -1.180052620608284, unseen = -4.04305126783455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 55}}),
       ("integer (3..19)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.4965075614664802,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 31},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074 \1095\1072\1089",
        Classifier{okData =
                     ClassData{prior = -0.15415067982725836,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -1.9459101490553135,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("integer (20..90)",
        Classifier{okData =
                     ClassData{prior = -0.6190392084062235,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -0.7731898882334817,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("<day-of-month> (ordinal or number) <named-month>",
        Classifier{okData =
                     ClassData{prior = -0.4353180712578455, unseen = -4.110873864173311,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081May",
                                     -2.995732273553991),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081September",
                                     -2.995732273553991),
                                    ("integer (numeric)September", -2.995732273553991),
                                    ("integer (numeric)May", -2.995732273553991),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081March",
                                     -2.995732273553991),
                                    ("month", -0.958850346292951),
                                    ("integer (numeric)June", -3.4011973816621555),
                                    ("integer (numeric)October", -2.70805020110221),
                                    ("integer (numeric)January", -2.70805020110221),
                                    ("integer (numeric)March", -2.3025850929940455)],
                               n = 22},
                   koData =
                     ClassData{prior = -1.041453874828161, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)May", -2.5902671654458267),
                                    ("ordinals (first..19th)September", -2.5902671654458267),
                                    ("ordinals (first..19th)February", -2.995732273553991),
                                    ("ordinals (first..19th)March", -2.3025850929940455),
                                    ("integer (numeric)February", -2.995732273553991),
                                    ("month", -1.1239300966523995),
                                    ("ordinals (20, 30,..,90)February", -2.995732273553991),
                                    ("integer (numeric)March", -2.5902671654458267)],
                               n = 12}}),
       ("<time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.1354942159291497,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -0.8938178760220964),
                                    ("tomorrowpart-of-days-2", -1.7047480922384253),
                                    ("\1074 <named-day>part-of-days-2", -2.3978952727983707),
                                    ("todaypart-of-days-2", -2.3978952727983707),
                                    ("day-after-tomorrowpart-of-days-2", -1.9924301646902063),
                                    ("Mondaypart-of-days-2", -2.3978952727983707)],
                               n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("numbers prefix with -, minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 1}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("at <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.25671984684781396,
                               unseen = -5.568344503761097,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> \1085\1086\1083\1100 0..9", -4.178226046202803),
                                    ("<time-of-day> <part-of-day>", -2.7313070632664775),
                                    ("half-short <hour-of-day-ordinal>", -4.465908118654584),
                                    ("<hour-of-day> <integer>", -2.6741486494265287),
                                    ("<hour-of-day> \1085\1086\1083\1100 0..9 \1084\1080\1085\1091\1090",
                                     -4.871373226762748),
                                    ("time-of-day (latent)", -1.7358790108335984),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090",
                                     -3.955082494888593),
                                    ("hh:mm", -2.4290261913935436),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)", -3.367295829986474),
                                    ("half-long <hour-of-day-ordinal>", -4.871373226762748),
                                    ("N \1095\1072\1089 (1..4, 22..23)", -4.178226046202803),
                                    ("hour", -1.330413902725434), ("minute", -1.539168716587544),
                                    ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
                                     -4.871373226762748)],
                               n = 123},
                   koData =
                     ClassData{prior = -1.4853852637641216, unseen = -4.477336814478207,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> <integer>", -2.856470206220483),
                                    ("time-of-day (latent)", -1.0001722158548572),
                                    ("hhmm (latent)", -3.7727609380946383),
                                    ("hour", -1.0001722158548572), ("minute", -2.6741486494265287)],
                               n = 36}}),
       ("September",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 1",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> \1087\1086\1087\1086\1083\1091\1076\1085\1080",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("N \1095\1072\1089 (1..4, 22..23)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("October",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("January",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1053\1086\1074\1099\1081 \1075\1086\1076",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Wednesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1056\1086\1078\1076\1077\1089\1090\1074\1086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> \1085\1086\1083\1100 0..9",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer (numeric)", -2.1972245773362196),
                                    ("time-of-day (latent)integer 0", -2.1972245773362196),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)integer 0",
                                     -2.1972245773362196),
                                    ("hour", -0.9444616088408514),
                                    ("at <time-of-day>integer (numeric)", -2.1972245773362196),
                                    ("at <time-of-day>integer 0", -1.791759469228055)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.16989903679539747,
                               unseen = -4.820281565605037,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1073\1077\1079 <integer> <hour-of-day>",
                                     -3.4258899942525267),
                                    ("\1074 \1095\1072\1089", -3.4258899942525267),
                                    ("at <time-of-day>", -1.9789710113162013),
                                    ("<hour-of-day> \1085\1086\1083\1100 0..9", -3.713572066704308),
                                    ("\1073\1077\1079 \1095\1077\1090\1074\1077\1088\1090\1080 <hour-of-day>",
                                     -3.713572066704308),
                                    ("half-short <hour-of-day-ordinal>", -3.202746442938317),
                                    ("<hour-of-day> <integer>", -2.866274206317104),
                                    ("time-of-day (latent)", -2.2472349979108808),
                                    ("hh:mm", -4.119037174812472),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)", -4.119037174812472),
                                    ("N \1095\1072\1089 (1..4, 22..23)", -3.713572066704308),
                                    ("hour", -1.3464484525726907), ("minute", -1.6341305250244718),
                                    ("\1088\1086\1074\1085\1086|\1090\1086\1095\1085\1086 <time-of-day>",
                                     -4.119037174812472),
                                    ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
                                     -4.119037174812472)],
                               n = 54},
                   koData =
                     ClassData{prior = -1.8562979903656263, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> <integer>", -2.456735772821304),
                                    ("time-of-day (latent)", -1.3581234841531944),
                                    ("hour", -1.3581234841531944), ("minute", -2.456735772821304)],
                               n = 10}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = -1.8718021769015913, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.1670540846631662,
                               unseen = -3.1780538303479458,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 22}}),
       ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<year> (latent)",
        Classifier{okData =
                     ClassData{prior = -1.1962507582320256,
                               unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList [("integer (numeric)", -0.25131442828090605)],
                               n = 13},
                   koData =
                     ClassData{prior = -0.36000273403140703, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.8472978603872037),
                                    ("integer (20..90)", -1.7635885922613588),
                                    ("numbers prefix with -, minus", -2.8622008809294686),
                                    ("integer 21..99", -2.456735772821304),
                                    ("integer 0", -1.3581234841531944)],
                               n = 30}}),
       ("\1074\1099\1093\1086\1076\1085\1099\1077",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1073\1077\1079 \1095\1077\1090\1074\1077\1088\1090\1080 <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half-short <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("", -0.8472978603872037),
                                    ("ordinals (first..19th)", -0.5596157879354228)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("May",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.7608058290337602, unseen = -5.662960480135946,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle><time-of-day> <part-of-day>",
                                     -4.966335035199676),
                                    ("hourday", -3.1745755659716206),
                                    ("dayhour", -2.075963277303511),
                                    ("daymonth", -3.094532858298084),
                                    ("monthyear", -3.462257638423402),
                                    ("tomorrowpart-of-days-2", -4.273187854639731),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month>(ordinal or number)/<named-month>/year",
                                     -4.966335035199676),
                                    ("intersectat <time-of-day>", -3.462257638423402),
                                    ("on <day>May", -4.966335035199676),
                                    ("<day-of-month> (ordinal)September", -4.560869927091511),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090intersect",
                                     -4.560869927091511),
                                    ("part-of-days-2<hour-of-day> <integer>", -4.966335035199676),
                                    ("<time-of-day> <part-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -4.560869927091511),
                                    ("October<year> \1075\1086\1076 (latent)", -4.560869927091511),
                                    ("October<year> (latent)", -4.273187854639731),
                                    ("todayat <time-of-day>", -4.560869927091511),
                                    ("at <time-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -4.560869927091511),
                                    ("<day-of-month> (ordinal)May", -4.560869927091511),
                                    ("<day-of-month> (ordinal or number) <named-month>at <time-of-day>",
                                     -4.966335035199676),
                                    ("<time> <part-of-day>at <time-of-day>", -4.560869927091511),
                                    ("on <day>September", -4.966335035199676),
                                    ("\1074 <named-day>part-of-days-2", -4.966335035199676),
                                    ("hourhour", -4.273187854639731),
                                    ("dayyear", -3.094532858298084),
                                    ("hourminute", -3.713572066704308),
                                    ("intersect<hour-of-day> <integer>", -4.966335035199676),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>at <time-of-day>",
                                     -4.966335035199676),
                                    ("at <time-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -4.560869927091511),
                                    ("part-of-days-2at <time-of-day>", -4.560869927091511),
                                    ("todaypart-of-days-2", -4.966335035199676),
                                    ("\1074(\1090\1077\1095\1077\1085\1080\1077)/\1085\1072 <named-month>|year<year> \1075\1086\1076 (latent)",
                                     -4.966335035199676),
                                    ("<time-of-day> <part-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -4.560869927091511),
                                    ("tomorrowintersect", -4.273187854639731),
                                    ("<time> <part-of-day><hour-of-day> <integer>",
                                     -4.966335035199676),
                                    ("<day-of-month> (ordinal or number) of <named-month><year> (latent)",
                                     -3.713572066704308),
                                    ("intersect<time-of-day> <part-of-day>", -4.560869927091511),
                                    ("intersect<year> (latent)", -4.560869927091511),
                                    ("<day-of-month>(ordinal or number)/<named-month>/yearat <time-of-day>",
                                     -4.273187854639731),
                                    ("day-after-tomorrowpart-of-days-2", -4.560869927091511),
                                    ("dayminute", -3.713572066704308),
                                    ("dd.mm.yyhh:mm", -4.966335035199676),
                                    ("on <day>March", -4.966335035199676),
                                    ("minuteday", -3.867722746531566),
                                    ("<day-of-month>(ordinal or number)/<named-month>/year<time-of-day> <part-of-day>",
                                     -4.966335035199676),
                                    ("<day-of-month> (ordinal or number) <named-month><year> (latent)",
                                     -3.713572066704308),
                                    ("today<time-of-day> <part-of-day>", -4.966335035199676),
                                    ("part-of-days-2\1074 <named-day>", -4.966335035199676),
                                    ("<day-of-month> (ordinal)March", -4.560869927091511),
                                    ("c <datetime> \1087\1086 <datetime> (interval)February",
                                     -4.560869927091511),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month> (ordinal or number) <named-month>",
                                     -4.966335035199676),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) <named-month>",
                                     -4.966335035199676),
                                    ("tomorrow<time-of-day> <part-of-day>", -4.966335035199676),
                                    ("tomorrowat <time-of-day>", -3.3568971227655755),
                                    ("Mondaypart-of-days-2", -4.966335035199676),
                                    ("<day-of-month> (ordinal or number) of <named-month>at <time-of-day>",
                                     -4.966335035199676),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month> (ordinal or number) of <named-month>",
                                     -4.966335035199676),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) of <named-month>",
                                     -4.966335035199676),
                                    ("\1074(\1090\1077\1095\1077\1085\1080\1077)/\1085\1072 <named-month>|year<year> (latent)",
                                     -4.560869927091511),
                                    ("c <datetime> \1087\1086 <datetime> (interval)March",
                                     -4.966335035199676),
                                    ("minuteyear", -4.560869927091511)],
                               n = 100},
                   koData =
                     ClassData{prior = -0.6297775666273561, unseen = -5.755742213586912,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -2.8081336596591924),
                                    ("dayhour", -3.5553480614894135),
                                    ("daymonth", -3.4499875458315876),
                                    ("monthyear", -3.8066624897703196),
                                    ("N \1095\1072\1089 (1..4, 22..23)<year> (latent)",
                                     -5.059425458265688),
                                    ("March<year> (latent)", -4.653960350157523),
                                    ("\1089 <time-of-day> \1087\1086 <time-of-day> (interval)March",
                                     -5.059425458265688),
                                    ("houryear", -2.169053700369523),
                                    ("intersectat <time-of-day>", -4.143134726391533),
                                    ("at <time-of-day>March", -5.059425458265688),
                                    ("<day-of-month> (ordinal)September", -4.653960350157523),
                                    ("time-of-day (latent)intersect", -3.4499875458315876),
                                    ("time-of-day (latent)October", -4.366278277705742),
                                    ("time-of-day (latent)January", -4.653960350157523),
                                    ("monthhour", -3.960813169597578),
                                    ("hourmonth", -2.4203681286504293),
                                    ("October<year> (latent)", -4.653960350157523),
                                    ("todayat <time-of-day>", -5.059425458265688),
                                    ("at <time-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -4.653960350157523),
                                    ("January<year> (latent)", -5.059425458265688),
                                    ("<day-of-month> (ordinal)May", -4.653960350157523),
                                    ("<time> <part-of-day>at <time-of-day>", -5.059425458265688),
                                    ("time-of-day (latent)September", -4.653960350157523),
                                    ("hourhour", -4.366278277705742),
                                    ("time-of-day (latent)February", -5.059425458265688),
                                    ("time-of-day (latent)June", -5.059425458265688),
                                    ("minutemonth", -4.366278277705742),
                                    ("June<year> (latent)", -5.059425458265688),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>at <time-of-day>",
                                     -5.059425458265688),
                                    ("<day-of-month> (ordinal)February", -4.653960350157523),
                                    ("at <time-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -4.653960350157523),
                                    ("part-of-days-2at <time-of-day>", -5.059425458265688),
                                    ("tomorrowintersect", -5.059425458265688),
                                    ("intersect<time-of-day> <part-of-day>", -5.059425458265688),
                                    ("intersect<year> (latent)", -3.5553480614894135),
                                    ("at <time-of-day>intersect", -4.653960350157523),
                                    ("Marchat <time-of-day>", -5.059425458265688),
                                    ("tomorrow<time-of-day> - <time-of-day> (interval)",
                                     -5.059425458265688),
                                    ("time-of-day (latent)March", -3.6731310971457973),
                                    ("at <time-of-day><year> (latent)", -2.7568403652716422),
                                    ("at <time-of-day>January", -5.059425458265688),
                                    ("<day-of-month> (ordinal)March", -4.366278277705742),
                                    ("c <datetime> \1087\1086 <datetime> (interval)February",
                                     -5.059425458265688),
                                    ("at <time-of-day>September", -5.059425458265688),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)<year> (latent)",
                                     -3.6731310971457973),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) <named-month>",
                                     -4.143134726391533),
                                    ("tomorrowat <time-of-day>", -4.143134726391533),
                                    ("\1089 <time-of-day> \1087\1086 <time-of-day> (interval)February",
                                     -5.059425458265688),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) of <named-month>",
                                     -4.143134726391533),
                                    ("c <datetime> \1087\1086 <datetime> (interval)March",
                                     -5.059425458265688),
                                    ("<hour-of-day> <integer>January", -4.653960350157523)],
                               n = 114}}),
       ("ordinals (20, 30,..,90)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = -0.4700036292457356,
                               unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("integer 21..99",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (20..90)integer (3..19)", -0.5108256237659907),
                                    ("integer (20..90)integer 2", -0.916290731874155)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.3862943611198906,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (20..90)integer (3..19)", -0.40546510810816444)],
                               n = 1}}),
       ("\1089\1087\1091\1089\1090\1103 <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("second", -1.791759469228055),
                                    ("<integer> \1089\1091\1090\1086\1082", -1.791759469228055),
                                    ("a <unit-of-duration>", -1.791759469228055),
                                    ("hour", -1.791759469228055), ("month", -1.791759469228055),
                                    ("<positive-numeral> <time-grain>", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074(\1090\1077\1095\1077\1085\1080\1077) <named-month>|year \1075\1086\1076\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("<year> (latent)", -0.6931471805599453),
                                    ("year", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Monday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1095\1077\1090\1074\1077\1088\1090\1100 <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("ordinals (first..19th)", 0.0)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm:ss",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("dd.mm.yy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> <integer>",
        Classifier{okData =
                     ClassData{prior = -0.23767165187711958,
                               unseen = -4.564348191467836,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>integer 21..99", -3.455264602932431),
                                    ("\1074 \1095\1072\1089integer (numeric)", -3.455264602932431),
                                    ("at <time-of-day>integer (20..90)", -3.455264602932431),
                                    ("time-of-day (latent)integer (numeric)", -1.988927534139004),
                                    ("time-of-day (latent)integer (3..19)", -3.455264602932431),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)integer (numeric)",
                                     -3.1675825304806504),
                                    ("time-of-day (latent)integer 21..99", -3.455264602932431),
                                    ("hour", -0.8162072733171726),
                                    ("at <time-of-day>integer (numeric)", -2.0689702418125404),
                                    ("at <time-of-day>integer (3..19)", -3.455264602932431),
                                    ("time-of-day (latent)integer (20..90)", -3.1675825304806504)],
                               n = 41},
                   koData =
                     ClassData{prior = -1.5533484457830569, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>integer 2", -2.8622008809294686),
                                    ("at <time-of-day>integer (20..90)", -2.456735772821304),
                                    ("time-of-day (latent)integer (numeric)", -2.169053700369523),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)integer (numeric)",
                                     -2.8622008809294686),
                                    ("hour", -1.0704414117014134),
                                    ("time-of-day (latent)integer 2", -2.8622008809294686),
                                    ("at <time-of-day>integer (numeric)", -2.8622008809294686),
                                    ("time-of-day (latent)integer (20..90)", -2.456735772821304)],
                               n = 11}}),
       ("<duration> \1089\1087\1091\1089\1090\1103|\1085\1072\1079\1072\1076",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("second", -1.791759469228055),
                                    ("<integer> \1089\1091\1090\1086\1082", -1.791759469228055),
                                    ("a <unit-of-duration>", -1.791759469228055),
                                    ("hour", -1.791759469228055), ("month", -1.791759469228055),
                                    ("<positive-numeral> <time-grain>", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("a <unit-of-duration>", -1.3862943611198906),
                                    ("hour", -1.3862943611198906)],
                               n = 1}}),
       ("\1074(\1090\1077\1095\1077\1085\1080\1077)/\1085\1072 <named-month>|year",
        Classifier{okData =
                     ClassData{prior = -0.325422400434628, unseen = -3.4965075614664802,
                               likelihoods =
                                 HashMap.fromList
                                   [("October", -2.367123614131617),
                                    ("<year> (latent)", -1.8562979903656263),
                                    ("year", -0.9808292530117262),
                                    ("<year> \1075\1086\1076 (latent)", -2.0794415416798357),
                                    ("month", -2.367123614131617),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>",
                                     -1.8562979903656263)],
                               n = 13},
                   koData =
                     ClassData{prior = -1.2809338454620642, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("<year> (latent)", -0.9808292530117262),
                                    ("year", -0.9808292530117262)],
                               n = 5}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> \1085\1086\1083\1100 0..9 \1084\1080\1085\1091\1090",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("N \1095\1072\1089\1086\1074 (0, 5..20)integer 0",
                                     -1.252762968495368),
                                    ("hour", -0.8472978603872037),
                                    ("at <time-of-day>integer 0", -1.252762968495368)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1083\1076\1077\1085\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal or number) of <named-month>",
        Classifier{okData =
                     ClassData{prior = -0.4353180712578455, unseen = -4.110873864173311,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081May",
                                     -2.995732273553991),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081September",
                                     -2.995732273553991),
                                    ("integer (numeric)September", -2.995732273553991),
                                    ("integer (numeric)May", -2.995732273553991),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081March",
                                     -2.995732273553991),
                                    ("month", -0.958850346292951),
                                    ("integer (numeric)June", -3.4011973816621555),
                                    ("integer (numeric)October", -2.70805020110221),
                                    ("integer (numeric)January", -2.70805020110221),
                                    ("integer (numeric)March", -2.3025850929940455)],
                               n = 22},
                   koData =
                     ClassData{prior = -1.041453874828161, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)May", -2.5902671654458267),
                                    ("ordinals (first..19th)September", -2.5902671654458267),
                                    ("ordinals (first..19th)February", -2.995732273553991),
                                    ("ordinals (first..19th)March", -2.3025850929940455),
                                    ("integer (numeric)February", -2.995732273553991),
                                    ("month", -1.1239300966523995),
                                    ("ordinals (20, 30,..,90)February", -2.995732273553991),
                                    ("integer (numeric)March", -2.5902671654458267)],
                               n = 12}}),
       ("\1101\1090\1086\1090 <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (grain)", -0.6931471805599453),
                                    ("year", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.639057329615259,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("by <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -1.0296194171811581),
                                    ("hh:mm", -1.9459101490553135), ("hour", -1.0296194171811581),
                                    ("minute", -1.9459101490553135)],
                               n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("June",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1089|\1087\1086\1089\1083\1077 <time>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -1.9459101490553135), ("day", -1.0986122886681098),
                                    ("time-of-day (latent)", -1.9459101490553135),
                                    ("<day-of-month> (ordinal)", -1.4350845252893227),
                                    ("hour", -1.9459101490553135)],
                               n = 8}}),
       ("February",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> \1089\1091\1090\1086\1082",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = -1.0498221244986778,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -0.4307829160924542, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13}}),
       ("time-of-day (latent)",
        Classifier{okData =
                     ClassData{prior = -0.6851790109107684, unseen = -4.219507705176107,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.4434925036974037),
                                    ("integer (3..19)", -1.160170181667543),
                                    ("integer 21..99", -3.5115454388310208)],
                               n = 63},
                   koData =
                     ClassData{prior = -0.7011793522572096, unseen = -4.204692619390966,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.1466034741918754),
                                    ("integer (3..19)", -3.4965075614664802),
                                    ("integer (20..90)", -2.3978952727983707)],
                               n = 62}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -1.4816045409242156, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.6094379124341003),
                                    ("integer 2week (grain)", -2.456735772821304),
                                    ("integer (numeric)week (grain)", -1.9459101490553135),
                                    ("integer (3..19)minute (grain)", -2.8622008809294686),
                                    ("integer (numeric)minute (grain)", -2.169053700369523),
                                    ("minute", -1.9459101490553135)],
                               n = 10},
                   koData =
                     ClassData{prior = -0.2578291093020998, unseen = -4.430816798843313,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)day (grain)", -2.8094026953624978),
                                    ("integer (3..19)day (grain)", -3.7256934272366524),
                                    ("integer 1hour (grain)", -3.7256934272366524),
                                    ("integer (numeric)year (grain)", -2.627081138568543),
                                    ("day", -2.627081138568543), ("year", -2.627081138568543),
                                    ("hour", -1.6462518855568167),
                                    ("integer (numeric)minute (grain)", -2.1162555148025524),
                                    ("integer (3..19)hour (grain)", -3.0325462466767075),
                                    ("minute", -2.1162555148025524),
                                    ("integer (numeric)hour (grain)", -1.9339339580085977)],
                               n = 34}}),
       ("<year> \1075\1086\1076 (latent)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinals (first..19th)",
        Classifier{okData =
                     ClassData{prior = -0.25131442828090605,
                               unseen = -3.1354942159291497,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 21},
                   koData =
                     ClassData{prior = -1.5040773967762742,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("hhmm (latent)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<hour-of-day> <integer> \1084\1080\1085\1091\1090",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.4657359027997265,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer (numeric)", -2.740840023925201),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)integer (numeric)",
                                     -1.824549292051046),
                                    ("N \1095\1072\1089 (1..4, 22..23)integer (numeric)",
                                     -2.740840023925201),
                                    ("N \1095\1072\1089\1086\1074 (0, 5..20)integer 0",
                                     -2.3353749158170367),
                                    ("hour", -0.8690378470236094),
                                    ("at <time-of-day>integer (numeric)", -2.3353749158170367),
                                    ("at <time-of-day>integer 0", -2.3353749158170367)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("on <day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.7376696182833684,
                               likelihoods =
                                 HashMap.fromList
                                   [("<day-of-month> (ordinal or number) <named-month>",
                                     -1.7676619176489945),
                                    ("intersect", -2.327277705584417),
                                    ("<day-of-month> (ordinal or number) of <named-month>",
                                     -1.7676619176489945),
                                    ("day", -0.7691330875378672),
                                    ("<day-of-month> (ordinal)", -2.327277705584417)],
                               n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("a <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -2.472930458741285, unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.159484249353372),
                                    ("month (grain)", -1.8718021769015913),
                                    ("hour (grain)", -2.5649493574615367),
                                    ("week (grain)", -2.159484249353372),
                                    ("minute (grain)", -2.5649493574615367),
                                    ("hour", -2.5649493574615367), ("month", -1.8718021769015913),
                                    ("minute", -2.5649493574615367)],
                               n = 7},
                   koData =
                     ClassData{prior = -8.81072675102669e-2, unseen = -5.10594547390058,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -3.153956278768885),
                                    ("hour (grain)", -1.8417698898027164),
                                    ("year (grain)", -2.2666530837679826),
                                    ("week (grain)", -3.153956278768885),
                                    ("day", -2.7019711550258276),
                                    ("minute (grain)", -2.1041341542702074),
                                    ("year", -2.2666530837679826), ("hour", -1.8417698898027164),
                                    ("minute", -2.1041341542702074),
                                    ("day (grain)", -2.7019711550258276)],
                               n = 76}}),
       ("hh:mm",
        Classifier{okData =
                     ClassData{prior = -7.696104113612832e-2,
                               unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 25},
                   koData =
                     ClassData{prior = -2.6026896854443837,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("\1085\1072 \1087\1088\1086\1096\1077\1076\1096\1077\1081 <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1074\1099\1093\1086\1076\1085\1099\1077",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("N \1095\1072\1089\1086\1074 (0, 5..20)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.3746934494414107),
                                    ("integer (3..19)", -1.6739764335716716),
                                    ("integer 0", -2.0794415416798357)],
                               n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute diminutive",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter of an hour",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1089 <time-of-day> \1087\1086 <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)time-of-day (latent)",
                                     -0.6931471805599453),
                                    ("hourhour", -0.6931471805599453)],
                               n = 2}}),
       ("\1089 <day-of-month> (ordinal or number) \1076\1086 <day-of-month> (ordinal or number) <named-month> (interval)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)ordinals (20, 30,..,90)February",
                                     -2.1972245773362196),
                                    ("integer (numeric)integer (numeric)February",
                                     -2.1972245773362196),
                                    ("ordinals (first..19th)ordinals (first..19th)February",
                                     -2.1972245773362196),
                                    ("ordinals (first..19th)ordinals (first..19th)March",
                                     -2.1972245773362196),
                                    ("integer (numeric)integer (numeric)March", -1.791759469228055),
                                    ("month", -0.9444616088408514)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("until <time>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -0.6931471805599453),
                                    ("day", -0.6931471805599453)],
                               n = 1}}),
       ("half-long <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("ordinals (first..19th)", 0.0)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("March",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("N \1095\1072\1089 (1..4, 22..23)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.8472978603872037),
                                    ("integer (3..19)", -1.252762968495368),
                                    ("integer 1", -1.252762968495368)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -0.3184537311185346, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081",
                                     -0.9985288301111273),
                                    ("ordinals (20, 30,..,90)", -1.845826690498331),
                                    ("ordinals (first..19th)", -0.7472144018302211)],
                               n = 16},
                   koData =
                     ClassData{prior = -1.2992829841302609,
                               unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)", -0.25131442828090605)],
                               n = 6}}),
       ("\1095\1077\1088\1077\1079|\1074 \1090\1077\1095\1077\1085\1080\1077|\1087\1086\1089\1083\1077 <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.07753744390572,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour diminutive", -2.6741486494265287),
                                    ("week", -1.8632184332102), ("second", -3.367295829986474),
                                    ("<integer> \1089\1091\1090\1086\1082", -3.367295829986474),
                                    ("<integer> <unit-of-duration>", -1.6625477377480489),
                                    ("a <unit-of-duration>", -2.268683541318364),
                                    ("minute diminutive", -2.9618307218783095),
                                    ("quarter of an hour", -3.367295829986474),
                                    ("hour", -2.268683541318364), ("month", -3.367295829986474),
                                    ("minute", -1.8632184332102),
                                    ("<positive-numeral> <time-grain>", -3.367295829986474)],
                               n = 23},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day-before-yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("decimal number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("<day-of-month>(ordinal or number)/<named-month>/year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("month", -0.8873031950009028),
                                    ("integer (numeric)June", -2.1400661634962708),
                                    ("integer (numeric)October", -1.7346010553881064),
                                    ("integer (numeric)January", -2.1400661634962708),
                                    ("integer (numeric)March", -1.7346010553881064)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> - <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -2.3025850929940455),
                                    ("hourhour", -0.916290731874155),
                                    ("minutehour", -2.3025850929940455),
                                    ("at <time-of-day>time-of-day (latent)", -0.916290731874155)],
                               n = 8}}),
       ("decimal one and a half",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1083\1085\1086\1095\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 0",
        Classifier{okData =
                     ClassData{prior = -0.4700036292457356,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (grain)", -0.8754687373538999),
                                    ("day", -2.4849066497880004), ("year", -0.8754687373538999),
                                    ("day (grain)", -2.4849066497880004)],
                               n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074 <named-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -0.6931471805599453), ("day", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -2.3025850929940455,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.10536051565782628,
                               unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9}}),
       ("part-of-days-2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("right now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1088\1086\1074\1085\1086|\1090\1086\1095\1085\1086 <time-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.3862943611198906),
                                    ("<time-of-day> <part-of-day>", -1.791759469228055),
                                    ("hour", -0.8754687373538999),
                                    ("\1087\1086\1083\1085\1086\1095\1100", -1.791759469228055)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("composite <duration>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourminute", -0.6931471805599453),
                                    ("integer (numeric)hour (grain)<integer> <unit-of-duration>",
                                     -0.6931471805599453)],
                               n = 4}}),
       ("day-after-tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<cycle> \1095\1077\1088\1077\1079 <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("minute (grain)integer (3..19)", -1.252762968495368),
                                    ("minute (grain)integer (numeric)", -1.252762968495368),
                                    ("minute", -0.8472978603872037)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)ordinals (first..19th)", 0.0)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<positive-numeral> <time-grain>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("decimal one and a halfhour (grain)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}})]