-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.RU_XX (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("c <datetime> \1087\1086 <datetime> (interval)",
        Classifier{okData =
                     ClassData{prior = -1.2039728043259361,
                               unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("MondayWednesday", -1.791759469228055),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal)",
                                     -2.1972245773362196),
                                    ("dayday", -1.5040773967762742)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.35667494393873245,
                               unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -2.159484249353372),
                                    ("time-of-day (latent)intersect", -2.5649493574615367),
                                    ("time-of-day (latent)time-of-day (latent)",
                                     -2.5649493574615367),
                                    ("dayday", -1.8718021769015913),
                                    ("<day-of-month> (ordinal)intersect", -2.5649493574615367),
                                    ("hourhour", -2.159484249353372),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal or number) <named-month>",
                                     -2.5649493574615367),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) <named-month>",
                                     -2.5649493574615367),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal or number) of <named-month>",
                                     -2.5649493574615367),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) of <named-month>",
                                     -2.5649493574615367)],
                               n = 7}}),
       ("\1073\1077\1079 <integer> <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -0.8266785731844679),
                                    ("integer (numeric)time-of-day (latent)", -1.6739764335716716),
                                    ("integer (3..19)time-of-day (latent)", -1.3862943611198906),
                                    ("integer (20..90)time-of-day (latent)", -2.0794415416798357)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour diminutive",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.3822082459438971, unseen = -4.770684624465665,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 116},
                   koData =
                     ClassData{prior = -1.1468143904859875, unseen = -4.02535169073515,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 54}}),
       ("integer (3..19)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.4965075614664802,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 31},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074 \1095\1072\1089",
        Classifier{okData =
                     ClassData{prior = -0.15415067982725836,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -1.9459101490553135,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("integer (20..90)",
        Classifier{okData =
                     ClassData{prior = -0.6190392084062235,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -0.7731898882334817,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("<day-of-month> (ordinal or number) <named-month>",
        Classifier{okData =
                     ClassData{prior = -0.3101549283038396, unseen = -4.060443010546419,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081May",
                                     -2.9444389791664407),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081September",
                                     -2.9444389791664407),
                                    ("integer (numeric)September", -2.9444389791664407),
                                    ("integer (numeric)May", -2.9444389791664407),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081March",
                                     -2.9444389791664407),
                                    ("month", -0.9075570519054005),
                                    ("integer (numeric)June", -3.349904087274605),
                                    ("integer (numeric)October", -2.6567569067146595),
                                    ("integer (numeric)January", -2.6567569067146595),
                                    ("integer (numeric)March", -2.2512917986064953)],
                               n = 22},
                   koData =
                     ClassData{prior = -1.3217558399823195,
                               unseen = -3.4011973816621555,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)May", -2.268683541318364),
                                    ("ordinals (first..19th)September", -2.268683541318364),
                                    ("ordinals (first..19th)March", -1.9810014688665833),
                                    ("month", -1.1700712526502546),
                                    ("integer (numeric)March", -2.6741486494265287)],
                               n = 8}}),
       ("<time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("tomorrowpart-of-days-2 (morning/day/evening)",
                                     -1.8971199848858813),
                                    ("dayhour", -0.916290731874155),
                                    ("todaypart-of-days-2 (morning/day/evening)",
                                     -2.3025850929940455),
                                    ("Mondaypart-of-days-2 (morning/day/evening)",
                                     -2.3025850929940455),
                                    ("\1074 <named-day>part-of-days-2 (morning/day/evening)",
                                     -2.3025850929940455),
                                    ("day-after-tomorrowpart-of-days-2 (morning/day/evening)",
                                     -1.8971199848858813)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("numbers prefix with -, minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 1}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("at <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.22793206804600688,
                               unseen = -5.583496308781699,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> \1085\1086\1083\1100 0..9", -4.193435464866331),
                                    ("<time-of-day> <part-of-day>", -2.7465164819300063),
                                    ("half-short <hour-of-day-ordinal>", -4.481117537318113),
                                    ("<hour-of-day> <integer>", -2.6893580680900575),
                                    ("1 \1095\1072\1089", -4.481117537318113),
                                    ("<hour-of-day> \1085\1086\1083\1100 0..9 \1084\1080\1085\1091\1090",
                                     -4.886582645426277),
                                    ("<time-of-day> \1095\1072\1089\1086\1074",
                                     -3.5002882843063863),
                                    ("time-of-day (latent)", -1.667706820558076),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090",
                                     -3.970291913552122),
                                    ("hh:mm", -2.444235610057073),
                                    ("half-long <hour-of-day-ordinal>", -4.886582645426277),
                                    ("hour", -1.3170499489449068), ("minute", -1.554378135251073),
                                    ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
                                     -4.886582645426277)],
                               n = 125},
                   koData =
                     ClassData{prior = -1.5905099025485814, unseen = -4.382026634673881,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> <integer>", -2.760009940032921),
                                    ("time-of-day (latent)", -1.0372433422918175),
                                    ("hhmm (latent)", -3.676300671907076),
                                    ("hour", -1.0372433422918175), ("minute", -2.5776883832389665)],
                               n = 32}}),
       ("September",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 1",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> \1087\1086\1087\1086\1083\1091\1076\1085\1080",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> \1095\1072\1089\1086\1074",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("October",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("January",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1053\1086\1074\1099\1081 \1075\1086\1076",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Wednesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1056\1086\1078\1076\1077\1089\1090\1074\1086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> \1085\1086\1083\1100 0..9",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer (numeric)", -2.3025850929940455),
                                    ("time-of-day (latent)integer 0", -2.3025850929940455),
                                    ("<time-of-day> \1095\1072\1089\1086\1074integer 0",
                                     -1.8971199848858813),
                                    ("hour", -0.916290731874155),
                                    ("at <time-of-day>integer (numeric)", -2.3025850929940455),
                                    ("at <time-of-day>integer 0", -1.8971199848858813)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.16989903679539747,
                               unseen = -4.820281565605037,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1073\1077\1079 <integer> <hour-of-day>",
                                     -3.4258899942525267),
                                    ("\1074 \1095\1072\1089", -3.4258899942525267),
                                    ("at <time-of-day>", -1.9789710113162013),
                                    ("<hour-of-day> \1085\1086\1083\1100 0..9", -3.713572066704308),
                                    ("\1073\1077\1079 \1095\1077\1090\1074\1077\1088\1090\1080 <hour-of-day>",
                                     -3.713572066704308),
                                    ("half-short <hour-of-day-ordinal>", -3.202746442938317),
                                    ("<hour-of-day> <integer>", -2.866274206317104),
                                    ("1 \1095\1072\1089", -3.713572066704308),
                                    ("<time-of-day> \1095\1072\1089\1086\1074", -4.119037174812472),
                                    ("time-of-day (latent)", -2.2472349979108808),
                                    ("hh:mm", -4.119037174812472), ("hour", -1.3464484525726907),
                                    ("minute", -1.6341305250244718),
                                    ("\1088\1086\1074\1085\1086|\1090\1086\1095\1085\1086 <time-of-day>",
                                     -4.119037174812472),
                                    ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
                                     -4.119037174812472)],
                               n = 54},
                   koData =
                     ClassData{prior = -1.8562979903656263, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> <integer>", -2.456735772821304),
                                    ("time-of-day (latent)", -1.3581234841531944),
                                    ("hour", -1.3581234841531944), ("minute", -2.456735772821304)],
                               n = 10}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = -1.791759469228055, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.1823215567939546,
                               unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20}}),
       ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<year> (latent)",
        Classifier{okData =
                     ClassData{prior = -1.148622709242771, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList [("integer (numeric)", -0.25131442828090605)],
                               n = 13},
                   koData =
                     ClassData{prior = -0.3813675565291038,
                               unseen = -3.5263605246161616,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.8574502318512216),
                                    ("integer (20..90)", -1.7047480922384253),
                                    ("numbers prefix with -, minus", -2.803360380906535),
                                    ("integer 21..99", -2.3978952727983707),
                                    ("integer 0", -1.4170660197866443)],
                               n = 28}}),
       ("\1074\1099\1093\1086\1076\1085\1099\1077",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1073\1077\1079 \1095\1077\1090\1074\1077\1088\1090\1080 <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half-short <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("", -0.8472978603872037),
                                    ("ordinals (first..19th)", -0.5596157879354228)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("May",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.7747271675523681, unseen = -5.655991810819852,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle><time-of-day> <part-of-day>",
                                     -4.959341999708705),
                                    ("tomorrowpart-of-days-2 (morning/day/evening)",
                                     -4.553876891600541),
                                    ("hourday", -3.1675825304806504),
                                    ("dayhour", -2.0689702418125404),
                                    ("daymonth", -3.0875398228071136),
                                    ("monthyear", -3.455264602932431),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month>(ordinal or number)/<named-month>/year",
                                     -4.959341999708705),
                                    ("part-of-days-2 (morning/day/evening)at <time-of-day>",
                                     -4.553876891600541),
                                    ("intersectat <time-of-day>", -3.455264602932431),
                                    ("todaypart-of-days-2 (morning/day/evening)",
                                     -4.959341999708705),
                                    ("on <day>May", -4.959341999708705),
                                    ("<day-of-month> (ordinal)September", -4.553876891600541),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090intersect",
                                     -4.553876891600541),
                                    ("Mondaypart-of-days-2 (morning/day/evening)",
                                     -4.959341999708705),
                                    ("<time-of-day> <part-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -4.553876891600541),
                                    ("<datetime> \1087\1086 <datetime> (interval) (latent)March",
                                     -4.553876891600541),
                                    ("October<year> \1075\1086\1076 (latent)", -4.553876891600541),
                                    ("October<year> (latent)", -4.26619481914876),
                                    ("todayat <time-of-day>", -4.553876891600541),
                                    ("at <time-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -4.553876891600541),
                                    ("<day-of-month> (ordinal)May", -4.553876891600541),
                                    ("<day-of-month> (ordinal or number) <named-month>at <time-of-day>",
                                     -4.959341999708705),
                                    ("<time> <part-of-day>at <time-of-day>", -4.553876891600541),
                                    ("on <day>September", -4.959341999708705),
                                    ("hourhour", -4.26619481914876),
                                    ("dayyear", -3.0875398228071136),
                                    ("\1074 <named-day>part-of-days-2 (morning/day/evening)",
                                     -4.959341999708705),
                                    ("part-of-days-2 (morning/day/evening)\1074 <named-day>",
                                     -4.959341999708705),
                                    ("hourminute", -3.7065790312133373),
                                    ("intersect<hour-of-day> <integer>", -4.959341999708705),
                                    ("part-of-days-2 (morning/day/evening)<hour-of-day> <integer>",
                                     -4.959341999708705),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>at <time-of-day>",
                                     -4.959341999708705),
                                    ("at <time-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -4.553876891600541),
                                    ("\1074(\1090\1077\1095\1077\1085\1080\1077)/\1085\1072 <named-month>|year<year> \1075\1086\1076 (latent)",
                                     -4.959341999708705),
                                    ("<time-of-day> <part-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -4.553876891600541),
                                    ("tomorrowintersect", -4.26619481914876),
                                    ("<time> <part-of-day><hour-of-day> <integer>",
                                     -4.959341999708705),
                                    ("<day-of-month> (ordinal or number) of <named-month><year> (latent)",
                                     -3.7065790312133373),
                                    ("day-after-tomorrowpart-of-days-2 (morning/day/evening)",
                                     -4.553876891600541),
                                    ("intersect<time-of-day> <part-of-day>", -4.553876891600541),
                                    ("intersect<year> (latent)", -4.553876891600541),
                                    ("<day-of-month>(ordinal or number)/<named-month>/yearat <time-of-day>",
                                     -4.26619481914876),
                                    ("dayminute", -3.7065790312133373),
                                    ("dd.mm.yyhh:mm", -4.959341999708705),
                                    ("on <day>March", -4.959341999708705),
                                    ("minuteday", -3.8607297110405954),
                                    ("<day-of-month>(ordinal or number)/<named-month>/year<time-of-day> <part-of-day>",
                                     -4.959341999708705),
                                    ("<day-of-month> (ordinal or number) <named-month><year> (latent)",
                                     -3.7065790312133373),
                                    ("today<time-of-day> <part-of-day>", -4.959341999708705),
                                    ("tomorrow<time-of-day> \1095\1072\1089\1086\1074",
                                     -4.959341999708705),
                                    ("<day-of-month> (ordinal)March", -4.553876891600541),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month> (ordinal or number) <named-month>",
                                     -4.959341999708705),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) <named-month>",
                                     -4.959341999708705),
                                    ("tomorrow<time-of-day> <part-of-day>", -4.959341999708705),
                                    ("tomorrowat <time-of-day>", -3.349904087274605),
                                    ("<day-of-month> (ordinal or number) of <named-month>at <time-of-day>",
                                     -4.959341999708705),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month> (ordinal or number) of <named-month>",
                                     -4.959341999708705),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) of <named-month>",
                                     -4.959341999708705),
                                    ("\1074(\1090\1077\1095\1077\1085\1080\1077)/\1085\1072 <named-month>|year<year> (latent)",
                                     -4.553876891600541),
                                    ("c <datetime> \1087\1086 <datetime> (interval)March",
                                     -4.959341999708705),
                                    ("minuteyear", -4.553876891600541)],
                               n = 100},
                   koData =
                     ClassData{prior = -0.6177234187427034, unseen = -5.768320995793772,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -2.820752123618404),
                                    ("dayhour", -3.5679665254486252),
                                    ("daymonth", -3.5679665254486252),
                                    ("monthyear", -3.8192809537295314),
                                    ("March<year> (latent)", -4.666578814116735),
                                    ("\1089 <time-of-day> \1087\1086 <time-of-day> (interval)March",
                                     -5.072043922224899),
                                    ("houryear", -2.051619036080537),
                                    ("part-of-days-2 (morning/day/evening)at <time-of-day>",
                                     -5.072043922224899),
                                    ("intersectat <time-of-day>", -4.155753190350744),
                                    ("at <time-of-day>March", -5.072043922224899),
                                    ("<day-of-month> (ordinal)September", -4.666578814116735),
                                    ("time-of-day (latent)intersect", -3.462606009790799),
                                    ("time-of-day (latent)October", -4.378896741664954),
                                    ("<datetime> \1087\1086 <datetime> (interval) (latent)March",
                                     -4.666578814116735),
                                    ("time-of-day (latent)January", -4.666578814116735),
                                    ("monthhour", -3.9734316335567894),
                                    ("hourmonth", -2.4693542367805157),
                                    ("October<year> (latent)", -4.666578814116735),
                                    ("todayat <time-of-day>", -5.072043922224899),
                                    ("at <time-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -4.666578814116735),
                                    ("January<year> (latent)", -5.072043922224899),
                                    ("<day-of-month> (ordinal)May", -4.666578814116735),
                                    ("<time> <part-of-day>at <time-of-day>", -5.072043922224899),
                                    ("time-of-day (latent)September", -4.666578814116735),
                                    ("hourhour", -4.378896741664954),
                                    ("time-of-day (latent)June", -5.072043922224899),
                                    ("minutemonth", -4.378896741664954),
                                    ("June<year> (latent)", -5.072043922224899),
                                    ("<time-of-day> \1095\1072\1089\1086\1074<year> (latent)",
                                     -3.200241745323308),
                                    ("\1089|\1087\1086\1089\1083\1077 <time>March",
                                     -4.666578814116735),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>at <time-of-day>",
                                     -5.072043922224899),
                                    ("at <time-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -4.666578814116735),
                                    ("tomorrowintersect", -5.072043922224899),
                                    ("intersect<time-of-day> <part-of-day>", -5.072043922224899),
                                    ("intersect<year> (latent)", -3.462606009790799),
                                    ("at <time-of-day>intersect", -4.666578814116735),
                                    ("Marchat <time-of-day>", -5.072043922224899),
                                    ("tomorrow<time-of-day> - <time-of-day> (interval)",
                                     -5.072043922224899),
                                    ("time-of-day (latent)March", -3.8192809537295314),
                                    ("at <time-of-day><year> (latent)", -2.7694588292308535),
                                    ("at <time-of-day>January", -5.072043922224899),
                                    ("<day-of-month> (ordinal)March", -4.378896741664954),
                                    ("at <time-of-day>September", -5.072043922224899),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) <named-month>",
                                     -4.155753190350744),
                                    ("tomorrowat <time-of-day>", -4.155753190350744),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) of <named-month>",
                                     -4.155753190350744),
                                    ("c <datetime> \1087\1086 <datetime> (interval)March",
                                     -5.072043922224899),
                                    ("<hour-of-day> <integer>January", -4.666578814116735)],
                               n = 117}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = -0.4700036292457356,
                               unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("integer 21..99",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (20..90)integer (3..19)", -0.5108256237659907),
                                    ("integer (20..90)integer 2", -0.916290731874155)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.3862943611198906,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (20..90)integer (3..19)", -0.40546510810816444)],
                               n = 1}}),
       ("\1089\1087\1091\1089\1090\1103 <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("second", -1.791759469228055),
                                    ("<integer> \1089\1091\1090\1086\1082", -1.791759469228055),
                                    ("a <unit-of-duration>", -1.791759469228055),
                                    ("hour", -1.791759469228055), ("month", -1.791759469228055),
                                    ("<positive-numeral> <time-grain>", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("part-of-days-2 (morning/day/evening)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074(\1090\1077\1095\1077\1085\1080\1077) <named-month>|year \1075\1086\1076\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("<year> (latent)", -0.6931471805599453),
                                    ("year", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Monday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1095\1077\1090\1074\1077\1088\1090\1100 <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("ordinals (first..19th)", 0.0)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm:ss",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("dd.mm.yy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> <integer>",
        Classifier{okData =
                     ClassData{prior = -0.23767165187711958,
                               unseen = -4.564348191467836,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>integer 21..99", -3.455264602932431),
                                    ("\1074 \1095\1072\1089integer (numeric)", -3.455264602932431),
                                    ("at <time-of-day>integer (20..90)", -3.455264602932431),
                                    ("time-of-day (latent)integer (numeric)", -1.988927534139004),
                                    ("time-of-day (latent)integer (3..19)", -3.455264602932431),
                                    ("time-of-day (latent)integer 21..99", -3.455264602932431),
                                    ("hour", -0.8162072733171726),
                                    ("<time-of-day> \1095\1072\1089\1086\1074integer (numeric)",
                                     -3.1675825304806504),
                                    ("at <time-of-day>integer (numeric)", -2.0689702418125404),
                                    ("at <time-of-day>integer (3..19)", -3.455264602932431),
                                    ("time-of-day (latent)integer (20..90)", -3.1675825304806504)],
                               n = 41},
                   koData =
                     ClassData{prior = -1.5533484457830569, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>integer 2", -2.8622008809294686),
                                    ("at <time-of-day>integer (20..90)", -2.456735772821304),
                                    ("time-of-day (latent)integer (numeric)", -2.169053700369523),
                                    ("hour", -1.0704414117014134),
                                    ("<time-of-day> \1095\1072\1089\1086\1074integer (numeric)",
                                     -2.8622008809294686),
                                    ("time-of-day (latent)integer 2", -2.8622008809294686),
                                    ("at <time-of-day>integer (numeric)", -2.8622008809294686),
                                    ("time-of-day (latent)integer (20..90)", -2.456735772821304)],
                               n = 11}}),
       ("1 \1095\1072\1089",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.6931471805599453),
                                    ("integer 1", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> \1089\1087\1091\1089\1090\1103|\1085\1072\1079\1072\1076",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("second", -1.791759469228055),
                                    ("<integer> \1089\1091\1090\1086\1082", -1.791759469228055),
                                    ("a <unit-of-duration>", -1.791759469228055),
                                    ("hour", -1.791759469228055), ("month", -1.791759469228055),
                                    ("<positive-numeral> <time-grain>", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("a <unit-of-duration>", -1.3862943611198906),
                                    ("hour", -1.3862943611198906)],
                               n = 1}}),
       ("\1074(\1090\1077\1095\1077\1085\1080\1077)/\1085\1072 <named-month>|year",
        Classifier{okData =
                     ClassData{prior = -0.2076393647782445,
                               unseen = -3.4965075614664802,
                               likelihoods =
                                 HashMap.fromList
                                   [("October", -2.367123614131617),
                                    ("<year> (latent)", -1.8562979903656263),
                                    ("year", -0.9808292530117262),
                                    ("<year> \1075\1086\1076 (latent)", -2.0794415416798357),
                                    ("month", -2.367123614131617),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>",
                                     -1.8562979903656263)],
                               n = 13},
                   koData =
                     ClassData{prior = -1.6739764335716716,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("<year> (latent)", -1.0986122886681098),
                                    ("year", -1.0986122886681098)],
                               n = 3}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> \1085\1086\1083\1100 0..9 \1084\1080\1085\1091\1090",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> \1095\1072\1089\1086\1074integer 0",
                                     -1.0986122886681098),
                                    ("hour", -0.8109302162163288),
                                    ("at <time-of-day>integer 0", -1.5040773967762742)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1083\1076\1077\1085\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal or number) of <named-month>",
        Classifier{okData =
                     ClassData{prior = -0.3101549283038396, unseen = -4.060443010546419,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081May",
                                     -2.9444389791664407),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081September",
                                     -2.9444389791664407),
                                    ("integer (numeric)September", -2.9444389791664407),
                                    ("integer (numeric)May", -2.9444389791664407),
                                    ("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081March",
                                     -2.9444389791664407),
                                    ("month", -0.9075570519054005),
                                    ("integer (numeric)June", -3.349904087274605),
                                    ("integer (numeric)October", -2.6567569067146595),
                                    ("integer (numeric)January", -2.6567569067146595),
                                    ("integer (numeric)March", -2.2512917986064953)],
                               n = 22},
                   koData =
                     ClassData{prior = -1.3217558399823195,
                               unseen = -3.4011973816621555,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)May", -2.268683541318364),
                                    ("ordinals (first..19th)September", -2.268683541318364),
                                    ("ordinals (first..19th)March", -1.9810014688665833),
                                    ("month", -1.1700712526502546),
                                    ("integer (numeric)March", -2.6741486494265287)],
                               n = 8}}),
       ("\1101\1090\1086\1090 <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (grain)", -0.6931471805599453),
                                    ("year", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 11},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> \1095\1072\1089\1086\1074",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.784189633918261,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.6817585740137264),
                                    ("time-of-day (latent)", -1.1221427860783038),
                                    ("hour", -0.7166776779701395)],
                               n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("June",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1089|\1087\1086\1089\1083\1077 <time>",
        Classifier{okData =
                     ClassData{prior = -2.772588722239781, unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -1.5040773967762742),
                                    ("<day-of-month> (ordinal)", -1.5040773967762742)],
                               n = 1},
                   koData =
                     ClassData{prior = -6.453852113757118e-2,
                               unseen = -3.6375861597263857,
                               likelihoods =
                                 HashMap.fromList
                                   [("intersect", -2.512305623976115),
                                    ("Monday", -2.512305623976115), ("day", -1.3083328196501787),
                                    ("time-of-day (latent)", -2.917770732084279),
                                    ("hour", -1.6650077635889111),
                                    ("<datetime> \1087\1086 <datetime> (interval) (latent)",
                                     -1.213022639845854)],
                               n = 15}}),
       ("<integer> \1089\1091\1090\1086\1082",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = -1.0498221244986778,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -0.4307829160924542, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13}}),
       ("time-of-day (latent)",
        Classifier{okData =
                     ClassData{prior = -0.579818495252942, unseen = -4.31748811353631,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.43286408229627876),
                                    ("integer (3..19)", -1.16857087727502),
                                    ("integer 21..99", -3.6109179126442243)],
                               n = 70},
                   koData =
                     ClassData{prior = -0.8209805520698302, unseen = -4.0943445622221,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.16551443847757344),
                                    ("integer (3..19)", -3.3843902633457743),
                                    ("integer (20..90)", -2.2857779746776643)],
                               n = 55}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -1.4816045409242156, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.6094379124341003),
                                    ("integer 2week (grain)", -2.456735772821304),
                                    ("integer (numeric)week (grain)", -1.9459101490553135),
                                    ("integer (3..19)minute (grain)", -2.8622008809294686),
                                    ("integer (numeric)minute (grain)", -2.169053700369523),
                                    ("minute", -1.9459101490553135)],
                               n = 10},
                   koData =
                     ClassData{prior = -0.2578291093020998, unseen = -4.430816798843313,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)day (grain)", -2.8094026953624978),
                                    ("integer (3..19)day (grain)", -3.7256934272366524),
                                    ("integer 1hour (grain)", -3.7256934272366524),
                                    ("integer (numeric)year (grain)", -2.627081138568543),
                                    ("day", -2.627081138568543), ("year", -2.627081138568543),
                                    ("hour", -1.6462518855568167),
                                    ("integer (numeric)minute (grain)", -2.1162555148025524),
                                    ("integer (3..19)hour (grain)", -3.0325462466767075),
                                    ("minute", -2.1162555148025524),
                                    ("integer (numeric)hour (grain)", -1.9339339580085977)],
                               n = 34}}),
       ("<year> \1075\1086\1076 (latent)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinals (first..19th)",
        Classifier{okData =
                     ClassData{prior = -0.3364722366212129, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 15},
                   koData =
                     ClassData{prior = -1.252762968495368, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("hhmm (latent)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<hour-of-day> <integer> \1084\1080\1085\1091\1090",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.6109179126442243,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer (numeric)", -2.890371757896165),
                                    ("<time-of-day> \1095\1072\1089\1086\1074integer 0",
                                     -1.9740810260220096),
                                    ("hour", -0.8109302162163288),
                                    ("<time-of-day> \1095\1072\1089\1086\1074integer (numeric)",
                                     -1.6376087894007967),
                                    ("at <time-of-day>integer (numeric)", -2.4849066497880004),
                                    ("at <time-of-day>integer 0", -2.4849066497880004)],
                               n = 15},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("on <day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.7376696182833684,
                               likelihoods =
                                 HashMap.fromList
                                   [("<day-of-month> (ordinal or number) <named-month>",
                                     -1.7676619176489945),
                                    ("intersect", -2.327277705584417),
                                    ("<day-of-month> (ordinal or number) of <named-month>",
                                     -1.7676619176489945),
                                    ("day", -0.7691330875378672),
                                    ("<day-of-month> (ordinal)", -2.327277705584417)],
                               n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("a <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -2.4485390056171257, unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.159484249353372),
                                    ("month (grain)", -1.8718021769015913),
                                    ("hour (grain)", -2.5649493574615367),
                                    ("week (grain)", -2.159484249353372),
                                    ("minute (grain)", -2.5649493574615367),
                                    ("hour", -2.5649493574615367), ("month", -1.8718021769015913),
                                    ("minute", -2.5649493574615367)],
                               n = 7},
                   koData =
                     ClassData{prior = -9.038406146826906e-2,
                               unseen = -5.081404364984463,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -3.1292636661785136),
                                    ("hour (grain)", -1.8971199848858813),
                                    ("year (grain)", -2.241960471177611),
                                    ("week (grain)", -3.1292636661785136),
                                    ("day", -2.6772785424354564),
                                    ("minute (grain)", -2.0794415416798357),
                                    ("year", -2.241960471177611), ("hour", -1.8971199848858813),
                                    ("minute", -2.0794415416798357),
                                    ("day (grain)", -2.6772785424354564)],
                               n = 74}}),
       ("hh:mm",
        Classifier{okData =
                     ClassData{prior = -8.004270767353637e-2,
                               unseen = -3.258096538021482,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 24},
                   koData =
                     ClassData{prior = -2.5649493574615367,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("\1085\1072 \1087\1088\1086\1096\1077\1076\1096\1077\1081 <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1074\1099\1093\1086\1076\1085\1099\1077",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute diminutive",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter of an hour",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1089 <time-of-day> \1087\1086 <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)time-of-day (latent)",
                                     -0.6931471805599453),
                                    ("hourhour", -0.6931471805599453)],
                               n = 1}}),
       ("\1089 <day-of-month> (ordinal or number) \1076\1086 <day-of-month> (ordinal or number) <named-month> (interval)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)ordinals (first..19th)March",
                                     -1.252762968495368),
                                    ("integer (numeric)integer (numeric)March", -1.252762968495368),
                                    ("month", -0.8472978603872037)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("until <time>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -0.6931471805599453),
                                    ("day", -0.6931471805599453)],
                               n = 1}}),
       ("half-long <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("ordinals (first..19th)", 0.0)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("March",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -0.5596157879354228,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (composite, e.g. \1074\1086\1089\1077\1084\1100\1076\1077\1089\1103\1090-\1087\1103\1090\1099\1081, \1089\1086\1088\1086\1082-\1089\1077\1076\1100\1084\1086\1081, \1076\1074\1072\1076\1074\1072\1090\1100-\1076\1077\1074\1103\1090\1099\1081, \1090\1088\1080\1076\1094\1072\1090\1100-\1090\1088\1077\1090\1080\1081",
                                     -0.35667494393873245),
                                    ("ordinals (first..19th)", -1.2039728043259361)],
                               n = 8},
                   koData =
                     ClassData{prior = -0.8472978603872037,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)", -0.13353139262452263)],
                               n = 6}}),
       ("\1095\1077\1088\1077\1079|\1074 \1090\1077\1095\1077\1085\1080\1077|\1087\1086\1089\1083\1077 <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.07753744390572,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour diminutive", -2.6741486494265287),
                                    ("week", -1.8632184332102), ("second", -3.367295829986474),
                                    ("<integer> \1089\1091\1090\1086\1082", -3.367295829986474),
                                    ("<integer> <unit-of-duration>", -1.6625477377480489),
                                    ("a <unit-of-duration>", -2.268683541318364),
                                    ("minute diminutive", -2.9618307218783095),
                                    ("quarter of an hour", -3.367295829986474),
                                    ("hour", -2.268683541318364), ("month", -3.367295829986474),
                                    ("minute", -1.8632184332102),
                                    ("<positive-numeral> <time-grain>", -3.367295829986474)],
                               n = 23},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day-before-yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<datetime> \1087\1086 <datetime> (interval) (latent)",
        Classifier{okData =
                     ClassData{prior = -1.791759469228055, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("<day-of-month> (ordinal)<day-of-month> (ordinal)",
                                     -2.1972245773362196),
                                    ("dayday", -1.791759469228055),
                                    ("\1089|\1087\1086\1089\1083\1077 <time><day-of-month> (ordinal)",
                                     -2.1972245773362196)],
                               n = 2},
                   koData =
                     ClassData{prior = -0.1823215567939546,
                               unseen = -3.5553480614894135,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -2.4277482359480516),
                                    ("time-of-day (latent)intersect", -2.833213344056216),
                                    ("MondayWednesday", -2.4277482359480516),
                                    ("time-of-day (latent)time-of-day (latent)",
                                     -2.833213344056216),
                                    ("dayday", -1.7346010553881064),
                                    ("<day-of-month> (ordinal)intersect", -2.833213344056216),
                                    ("hourhour", -2.1400661634962708),
                                    ("\1089|\1087\1086\1089\1083\1077 <time>time-of-day (latent)",
                                     -2.833213344056216),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal or number) <named-month>",
                                     -2.833213344056216),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) <named-month>",
                                     -2.833213344056216),
                                    ("<day-of-month> (ordinal)<day-of-month> (ordinal or number) of <named-month>",
                                     -2.833213344056216),
                                    ("time-of-day (latent)<day-of-month> (ordinal or number) of <named-month>",
                                     -2.833213344056216)],
                               n = 10}}),
       ("decimal number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("<day-of-month>(ordinal or number)/<named-month>/year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("month", -0.8873031950009028),
                                    ("integer (numeric)June", -2.1400661634962708),
                                    ("integer (numeric)October", -1.7346010553881064),
                                    ("integer (numeric)January", -2.1400661634962708),
                                    ("integer (numeric)March", -1.7346010553881064)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> - <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -2.3025850929940455),
                                    ("hourhour", -0.916290731874155),
                                    ("minutehour", -2.3025850929940455),
                                    ("at <time-of-day>time-of-day (latent)", -0.916290731874155)],
                               n = 8}}),
       ("decimal one and a half",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1083\1085\1086\1095\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 0",
        Classifier{okData =
                     ClassData{prior = -0.5596157879354228, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.8472978603872037,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (grain)", -0.8754687373538999),
                                    ("day", -2.4849066497880004), ("year", -0.8754687373538999),
                                    ("day (grain)", -2.4849066497880004)],
                               n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074 <named-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -0.6931471805599453), ("day", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -2.3025850929940455,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.10536051565782628,
                               unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9}}),
       ("right now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1088\1086\1074\1085\1086|\1090\1086\1095\1085\1086 <time-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.3862943611198906),
                                    ("<time-of-day> <part-of-day>", -1.791759469228055),
                                    ("hour", -0.8754687373538999),
                                    ("\1087\1086\1083\1085\1086\1095\1100", -1.791759469228055)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("composite <duration>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourminute", -0.6931471805599453),
                                    ("integer (numeric)hour (grain)<integer> <unit-of-duration>",
                                     -0.6931471805599453)],
                               n = 4}}),
       ("day-after-tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<cycle> \1095\1077\1088\1077\1079 <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("minute (grain)integer (3..19)", -1.252762968495368),
                                    ("minute (grain)integer (numeric)", -1.252762968495368),
                                    ("minute", -0.8472978603872037)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)ordinals (first..19th)", 0.0)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<positive-numeral> <time-grain>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("decimal one and a halfhour (grain)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}})]